---

plugins:
  - react
  - functional

extends:
  - airbnb
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true
  es6: true

settings:
  import/resolver:
    - node
    - webpack:
        config: 'webpack.config.cjs'

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - state
  no-shadow:
    - error
    - allow:
      - addChannel
      - removeChannel
      - renameChannel
